name: CI Pipeline

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: write
  statuses: write

jobs:
  comment-rocket:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.comment.body, 'rocket') }}
    steps:
      - run: echo "Commnet Rocket"

  deploy-preview:
    if: ${{ contains(github.event.comment.body, 'rocket') && github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Github API Request
        id: request
        uses: octokit/request-action@v2.0.0
        with:
          route: ${{ github.event.issue.pull_request.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout PR Branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ fromJson(steps.request.outputs.data).head.repo.full_name }}
          ref: ${{ fromJson(steps.request.outputs.data).head.ref }}

      - name: Starting Deployment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ github.event.comment.id }}
          body: |
            ### :rocket: Deployed Preview :rocket:

            Deployment in progress...
          edit-mode: replace


      - name: Deploy Preview
        run: echo "Deploying preview"

      - name: Update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ github.event.comment.id }}
          body: |
            ### :rocket: Deployed Preview :rocket:

            **Deployment complete**. [View deployment](https://example.com)
          edit-mode: replace
