name: CI Pipeline

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: write
  statuses: write

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - run: echo "Linting code"

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - run: echo "Building code"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Testing code"
      
  comment-approval:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Comment on Issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### :green_circle: Deploy Preview :green_circle:

            **Ready for deployment**: Comment with "deploy" to start deployment.

  deploy-preview:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'issue_comment' && contains(github.event.comment.body, 'deploy') }}
    steps:
      - name: Checkout pull request 🏁
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
          
      - uses: myrotvorets/set-commit-status-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: Publish NPM package

      - uses: thollander/actions-comment-pull-request@v2
        with:
          mode: create
          comment_tag: deploy
          message: |
            ### :rocket: Deploying Preview :rocket:

            **Deployment in progress**. Please wait for the deployment to complete.

      - uses: myrotvorets/set-commit-status-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: success
          context: Publish NPM package

      - uses: thollander/actions-comment-pull-request@v2
        with:
          mode: recreate
          comment_tag: deploy
          message: |
            ### :rocket: Deploying Preview :rocket:

            **Deployment completed**. You can now view the deployed preview at [https://my-preview-url.com](https://my-preview-url.com).

