name: CI Pipeline

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: write
  statuses: write

jobs:
  comment-rocket:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.comment.body, 'rocket') }}
    steps:
      - run: echo "Commnet Rocket"

  react-rocket:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.reactions.rocket > 0 }}
    steps:
      - run: echo "React Rocket"

  deploy-preview:
    if: ${{ contains(github.event.comment.body, 'deploy') && github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Starting Deployment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ github.event.comment.id }}
          body: |
            ### :rocket: Deployed Preview :rocket:

            Deployment in progress...
          edit-mode: replace


      - name: Add commit status
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.issue.number;
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });
            const prSha = pullRequest.head.sha;
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: prSha,
              state: 'pending',
              context: 'Deploy Preview',
              description: 'Deployment in progress...'
            })

      - name: Deploy Preview
        run: echo "Deploying preview"

      - name: Update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ github.event.comment.id }}
          body: |
            ### :rocket: Deployed Preview :rocket:

            **Deployment complete**. [View deployment](https://example.com)
          edit-mode: replace

      - name: Add commit status
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.issue.number;
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });
            const prSha = pullRequest.head.sha;
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: prSha,
              state: 'success',
              context: 'Deploy Preview',
              description: 'Deployment in progress...'
            })