name: CI Pipeline

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: write
  statuses: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Starting Deployment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ github.event.comment.id }}
          body: |
            ### :rocket: Deployed Preview :rocket:

            Deployment in progress...
          edit-mode: replace

      - name: Add commit status
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_sha = context.payload.issue.pull_request.head.sha
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: pr_sha,
              state: 'pending',
              context: 'Deploy Preview',
              description: 'Deployment in progress...'
            })

      - name: Deploy Preview
        run: echo "Deploying preview"

      - name: Update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ github.event.comment.id }}
          body: |
            ### :rocket: Deployed Preview :rocket:

            **Deployment complete**. [View deployment](https://example.com)
          edit-mode: replace

      - name: Add commit status
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_sha = context.payload.issue.pull_request.head.sha
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: pr_sha,
              state: 'success',
              context: 'Deploy Preview',
              description: 'Deployment complete'
            })