name: CI Pipeline

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Starting Deployment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ github.event.comment.id }}
          body: |
            ### :rocket: Deployed Preview :rocket:

            Deployment in progress...
          edit-mode: replace
          
      - name: Add commit status
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'pending',
              context: 'Deploy Preview',
              description: 'Deployment in progress...'
            })