name: CI Pipeline

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "Linting code"

  # build:
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   steps:
  #     - run: echo "Building code"
      
  comment-approval:
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: vianaz
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

  deploy:
    runs-on: ubuntu-latest
    needs: comment-approval
    steps:
      - run: echo "Deploying code"
