name: CI Pipeline

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Linting code"

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - run: echo "Building code"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Testing code"
      
  comment-approval:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Comment on Issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### :green_circle: Deploy Preview :green_circle:

            **Ready for deployment**: Comment with "deploy" to start deployment.

